Agent for Ppc64le
digiaiiris/zabbix-agent pull request #14
Opened 2021-03-16 15:31 UTC by DigJurppe

**Still lacks testing and best practices**

Installation package for RHEL 7.6 (ppc64le)

Contains:
* installation package, which includes 
  * binaries from Official Zabbix -site
  * some custom monitoring scripts
  * init file, which might not be necassary
  * service file for systemd

* Installation script
  * Creates user and group for zabbix
  * Create necessary directories for
    * agent (/etc/zabbix)
    * log files (/var/log/zabbix)
    * pid files (/var/run/zabbix)
  * extracts 
    * agent binaries, configurations and scripts to /etc/zabbix
    * service file to /etc/systemd/system/multi-user.target.wants
  * modifies file permissions to be in ownership of the zabbix -user

* Uninstallation script (low effort)

2021-03-17 07:58 UTC, sapajune requested changes
Clean work. I think this needs some more ironing though.

Additional comments:
- What is the reason for having empty files in version control: zabbix_agent-5.0.8-linux-ppc64le.tar, zabbix_get and zabbix_sender?
- I don't see anything that properly configures the zabbix_agentd.conf. How is that supposed to happen?

2021-03-17 07:58 UTC, sapajune commented on archive/readme.md
> +`tar -zxvf zabbix_agent-5.0.8-linux-ppc64le.tar.gz zabbix_agent`
Seems more like extract to me. Where does the tar.gz come from?

2021-03-17 07:58 UTC, sapajune commented on archive/zabbix-install
> +tar xvf zabbix_agent-5.0.8-linux-ppc64le.tar
Is there reason not to do all this in one step using tar's z flag (like having tar from 90's)?

2021-03-17 07:58 UTC, sapajune commented on archive/zabbix-install
> +chmod -R o+r /var/run/zabbix
I think it would also be possible to build tar file with absolute paths and permissions so it extracts directly to correct folders with necessary permissions (as long as corresponding users and groups already exist) but this works too.

2021-03-17 07:58 UTC, sapajune commented on archive/zabbix-install
> +
Should this have set -e?

2021-03-17 07:58 UTC, sapajune commented on archive/readme.md
> +
Mixed agent versions across files. This has 5.0.9, elsewhere 5.0.8.

2021-03-17 07:58 UTC, sapajune commented on archive/zabbix-install
> +elif [ ! -e zabbix_agent-5.0.8-linux-ppc64le.tar.gz ]; then
Version number (5.0.8) is used in several places of script. Declare it as variable (e.g. AGENT_VERSION) at start of script and use that so changing version doesn't require multiple modifications that are hard to verify for correctness.

2021-03-17 07:58 UTC, sapajune commented on archive/readme.md
> +Deliver the contents of `archive/` directory.
I don't see how these instructions actually provide the files required for installation.

Delivering folder of files to customer is not really straightforward either. Packaging process should provide single file (e.g. tar.gz) that can be sent with instructions on extracting and running install script.

2021-03-18 06:48 UTC, kompa3 commented on archive/zabbix_agent/conf/zabbix_agentd.conf
> +ServerActive=digiaiirisproxy.sok.fi
This is SOK specific. To make this general, I suggest that zabbix-install script asks (prompts) for the server address and Tieto is instructed to type in the correct address.

2021-03-18 06:51 UTC, kompa3 commented on archive/zabbix_agent/conf/zabbix_agentd.conf
> +Include=/etc/zabbix/zabbix_agentd/*.conf
This assumes that .conf files are under /etc/zabbix/zabbix_agentd/. However, zabbix-install script copies them to /etc/zabbix/conf.

2021-03-18 06:55 UTC, kompa3 commented on archive/readme.md
> +# Zabbix Agent (Iiris)
I suggest that `archive` folder is renamed to ppc64le since this package is ppc64 specific.

2021-03-18 06:58 UTC, kompa3 commented on archive/readme.md
> +Deliver the contents of `archive/` directory.
I suggest to add the building of the release package to `build-all.sh` script under the root directory of the repository. So that ppc64le package will be built and released in a scripted fashion alongside the other distros.

2021-03-18 07:01 UTC, kompa3 commented on archive/readme.md
> +
Actually I don't quite understand why the binaries are in the github repository in two places: both in zabbix_agent-5.0.8-linux-ppc64le.tar package and also unpacked (eg. sbin/zabbix_agentd). Having the tar package in github makes it easier to update to newer agent versions. What if the unpacked files in git were regular text files containing "placeholder" text or something like that?

2021-03-18 07:24 UTC, kompa3 commented on archive/zabbix-install
> +echo "to start agent, use command"
Please add instruction to enable the service too for every reboot

2021-03-30 14:16 UTC, DigJurppe commented on archive/readme.md
> +`tar -zxvf zabbix_agent-5.0.8-linux-ppc64le.tar.gz zabbix_agent`
oops

2021-03-30 14:17 UTC, DigJurppe commented on archive/readme.md
> +
added configuration variables

2021-03-30 14:17 UTC, DigJurppe commented on archive/zabbix-install
> +elif [ ! -e zabbix_agent-5.0.8-linux-ppc64le.tar.gz ]; then
fixd

2021-03-30 14:18 UTC, DigJurppe commented on archive/zabbix_agent/conf/zabbix_agentd.conf
> +ServerActive=digiaiirisproxy.sok.fi
added configuration variable for this

2021-03-30 14:18 UTC, DigJurppe commented on archive/zabbix_agent/conf/zabbix_agentd.conf
> +Include=/etc/zabbix/zabbix_agentd/*.conf
oops

2021-03-30 14:18 UTC, DigJurppe commented on archive/readme.md
> +
mby now?

2021-03-30 14:18 UTC, DigJurppe commented on archive/zabbix-install
> +echo "to start agent, use command"
done

2021-04-01 06:31 UTC, sapajune reviewed
Looks great! Address the comments and it's ready to ship. 😄

2021-04-01 06:31 UTC, sapajune commented on ppc64le/build.sh
> +chown -R zabbix:zabbix zabbix_build/etc/zabbix/*
Note that this requires zabbix user and group to exist on build machine. Possibly something to include in instructions.

2021-04-01 06:31 UTC, sapajune commented on ppc64le/readme.md
> +`./zabbix-uninstall`
Should install/uninstall be ran with sudo?

2021-04-01 06:31 UTC, sapajune commented on ppc64le/readme.md
> +* **zabbix-agent-init-deprecated**
So init script is deprecated and not used at all? Should at least have explanation why it's being preserved.

2021-04-01 06:31 UTC, sapajune commented on ppc64le/readme.md
> +## Contents
Contents list should explain purpose of each entry. Otherwise it has no real meaning.

2021-04-08 08:46 UTC, kompa3 commented on ppc64le/build.sh
> +chown -R zabbix:zabbix zabbix_build/etc/zabbix/*
Is there a danger that the target machine has different pid&gid for zabbix or root users? Does the installation now rely on that untarring the package sets the correct ownership for the files?
I suggest that instead the tar package is created with the "normal" user rights (no zabbix or root) and that `zabbix-install` sets explicitly the user rights for each file.

2021-04-08 08:50 UTC, kompa3 commented on ppc64le/build.sh
> +chown -R zabbix:zabbix zabbix_build/etc/zabbix/*
Also, `build.sh` must now be run with `sudo` which is not very good

2021-04-08 08:54 UTC, kompa3 commented on ppc64le/build.sh
> +sed -i "s/ServerActive=127.0.0.1/ServerActive=$ACTIVE_HOST/g" zabbix_build/etc/zabbix/zabbix_agentd.conf
`zabbix_agentd.conf` now has the following uncommented line, I think it should be commented/deleted:
`Hostname=Zabbix server`

2021-04-08 08:56 UTC, kompa3 commented on ppc64le/build.sh
> +sed -i "s/ServerActive=127.0.0.1/ServerActive=$ACTIVE_HOST/g" zabbix_build/etc/zabbix/zabbix_agentd.conf
Should the configuration file have TLS/PSK settings in place or are they configured manually?

2021-04-08 08:56 UTC, kompa3 commented on ppc64le/build.sh
> +cp -a externalconf/. zabbix_build/etc/zabbix/zabbix_agentd.conf.d/
This does not use `INCLUDE_PATH` variable from `options.cfg`

2021-04-08 08:57 UTC, kompa3 commented on ppc64le/options.cfg
> +INCLUDE_PATH="/etc/zabbix/zabbix_agentd.conf.d/*.conf"
I suggest we use `/etc/zabbix/zabbix_agentd.d` as is the normal practice with RHEL and Debian installation packages

2021-04-08 08:59 UTC, kompa3 commented on ppc64le/externalscripts/example.sh
> +echo "1"
I suggest that we include at least `process.sh` and `process.conf` from https://github.com/digiapulssi/zabbix-monitoring-scripts/blob/master/etc/zabbix/ to enable top process monitoring. By now I think we could just copy the file here in Git.

2021-04-08 09:00 UTC, kompa3 commented on ppc64le/build.sh
> +cp -a externalscripts/. zabbix_build/etc/zabbix/scripts/
Please add +x flag to the externalscripts, either in `build.sh` or in-place in git. Now `example.sh` does not have execute flag.

2021-04-08 09:04 UTC, kompa3 requested changes
I think this new architecture is a good way to go. A few remarks, however.

2021-04-08 11:03 UTC, sapajune commented on ppc64le/build.sh
> +chown -R zabbix:zabbix zabbix_build/etc/zabbix/*
To my understanding tar doesn't store permissions as uid/gid but actual names. Agree that sudo requirement is not very good. I didn't think of that when I suggested tar permissions might be used instead of multi-step permission changes and copies. 😄

Note that changing permissions should be done very carefully avoiding changing any other files that may be present in the system.

2021-04-08 11:07 UTC, sapajune commented
> I think this new architecture is a good way to go. A few remarks, however.

I think relying on git with execute flag is a bit dangerous since apparently commits from Windows may inadvertently unset that.

2021-04-12 06:12 UTC, kompa3 commented on ppc64le/build.sh
> +echo "./zabbix-install"
sudo ./zabbix-install (at least if you're not running under root user)

2021-04-12 06:13 UTC, kompa3 commented on ppc64le/zabbix-install
> +if [ -e /tmp/zabbix_agent/zabbix-agent.service ]; then
This check happens from an incorrect (old) directory, should be from the same as where the script is

2021-04-12 06:16 UTC, kompa3 commented on ppc64le/zabbix-install
> +chown -R zabbix:zabbix /tmp/zabbix_agent/etc/
psk.key will now have the following privileges:
`-rw-rw-r--.   1 zabbix zabbix    14 Apr 12 06:06 psk.key`

I don't think if it is an issue for zabbix agent but normally PSK keys should not have read access for every user (o+r)

2021-04-12 06:18 UTC, kompa3 commented on ppc64le/zabbix-install
> +mv -i /tmp/zabbix_agent/usr/sbin/zabbix_agentd /usr/sbin/
These should be owned by root

2021-04-12 06:22 UTC, kompa3 commented on ppc64le/zabbix-install
> +  mv zabbix-agent.service /etc/systemd/system/multi-user.target.wants/
Service file should be owned by `root` user. Also, I am not sure if it matters but all other service files have execute flag so I assume this one should too.

2021-04-12 06:23 UTC, kompa3 requested changes
Good, I tested the package and added a few more comments. Still I'd suggest you include process monitoring script here.

2021-04-15 07:57 UTC, DigJurppe commented on ppc64le/zabbix-install
> +chown -R zabbix:zabbix /tmp/zabbix_agent/etc/
fixed https://github.com/digiaiiris/zabbix-agent/pull/14/commits/4b938e8c7dacb02940fe75e2611cf0cdc785a49c

2021-04-15 08:15 UTC, DigJurppe commented on ppc64le/zabbix-install
> +mv -i /tmp/zabbix_agent/usr/sbin/zabbix_agentd /usr/sbin/
I think they were, but now chowning binaries via install-script

2021-04-15 08:18 UTC, DigJurppe commented on ppc64le/build.sh
> +cp -a externalscripts/. zabbix_build/etc/zabbix/scripts/
modified in git

2021-04-15 08:19 UTC, DigJurppe commented on ppc64le/zabbix-install
> +  mv zabbix-agent.service /etc/systemd/system/multi-user.target.wants/
added +x in git.

2021-04-15 08:25 UTC, DigJurppe commented on ppc64le/zabbix-install
> +if [ -e /tmp/zabbix_agent/zabbix-agent.service ]; then
fixed https://github.com/digiaiiris/zabbix-agent/pull/14/commits/4901a1839e1d00b50e6281c74f84516571f0089f

2021-04-15 08:25 UTC, DigJurppe commented on ppc64le/build.sh
> +echo "./zabbix-install"
fixed https://github.com/digiaiiris/zabbix-agent/pull/14/commits/eb58b757edf836507d92dd0e1711e6a374c8c91d

2021-04-15 08:26 UTC, DigJurppe commented on ppc64le/externalscripts/example.sh
> +echo "1"
fixed https://github.com/digiaiiris/zabbix-agent/pull/14/commits/4901a1839e1d00b50e6281c74f84516571f0089f

2021-04-15 08:27 UTC, DigJurppe commented on ppc64le/options.cfg
> +INCLUDE_PATH="/etc/zabbix/zabbix_agentd.conf.d/*.conf"
fixed https://github.com/digiaiiris/zabbix-agent/pull/14/commits/eb58b757edf836507d92dd0e1711e6a374c8c91d

2021-04-15 08:27 UTC, DigJurppe commented on ppc64le/build.sh
> +cp -a externalconf/. zabbix_build/etc/zabbix/zabbix_agentd.conf.d/
fixed https://github.com/digiaiiris/zabbix-agent/pull/14/commits/eb58b757edf836507d92dd0e1711e6a374c8c91d

2021-04-15 08:28 UTC, DigJurppe commented on ppc64le/build.sh
> +sed -i "s/ServerActive=127.0.0.1/ServerActive=$ACTIVE_HOST/g" zabbix_build/etc/zabbix/zabbix_agentd.conf
agent configuration now in build.sh based on options.cfg variables https://github.com/digiaiiris/zabbix-agent/pull/14/commits/eb58b757edf836507d92dd0e1711e6a374c8c91d

2021-04-15 12:26 UTC, kompa3 approved these changes

2021-04-15 12:43 UTC, sapajune approved these changes

2021-04-15 12:45 UTC, ilniemi approved these changes

2021-05-05 11:17 UTC, merged